/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.ausiasmarch_calculocalorías.gui;

import net.ausiasmarch.common.Convert;
import net.ausiasmarch_calculocalorías.model.MetabolismoBasal;
import net.ausiasmarch_calculocalorías.model.TipoActividad;

/**
 *
 * @author a0y3770325h
 */
public class Main extends javax.swing.JFrame {

    private MetabolismoBasal metaBasal;

    /**
     * Creates new form CalculoCalorías
     */
    public Main() {
        initComponents();

        metaBasal = new MetabolismoBasal();

        setSize(550, 450);
        setLocationRelativeTo(null);
        jPanelErrores.setVisible(false);

        jComboBoxActividad.addItem(TipoActividad.SEDENTARIA.toString());
        jComboBoxActividad.addItem(TipoActividad.LIGERA.toString());
        jComboBoxActividad.addItem(TipoActividad.MODERADA.toString());
        jComboBoxActividad.addItem(TipoActividad.INTENSA.toString());
        jComboBoxActividad.addItem(TipoActividad.MUY_INTENSA.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelGenero = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        jLabelPeso = new javax.swing.JLabel();
        jTextFieldPeso = new javax.swing.JTextField();
        jLabel_kg = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jTextFieldAltura = new javax.swing.JTextField();
        jLabel_cm = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel_años = new javax.swing.JLabel();
        jLabelActividad = new javax.swing.JLabel();
        jComboBoxActividad = new javax.swing.JComboBox<>();
        jButtonCalcular = new javax.swing.JButton();
        jLabelMetabolismo = new javax.swing.JLabel();
        jTextFieldMetBas = new javax.swing.JTextField();
        jLabelkcal = new javax.swing.JLabel();
        jLabelCalMantPeso = new javax.swing.JLabel();
        jTextFieldMantPes = new javax.swing.JTextField();
        jLabelkc = new javax.swing.JLabel();
        jLabelCC = new javax.swing.JLabel();
        jPanelErrores = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaErrores = new javax.swing.JTextArea();
        jButtonCerrarErrores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelGenero.setText("Género");

        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        jLabelPeso.setText("Peso");

        jTextFieldPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoActionPerformed(evt);
            }
        });

        jLabel_kg.setText("kg");

        jLabelAltura.setText("Altura");

        jLabel_cm.setText("cm");

        jLabelEdad.setText("Edad");

        jLabel_años.setText("años");

        jLabelActividad.setText("Actividad");

        jComboBoxActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActividadActionPerformed(evt);
            }
        });

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.setMargin(new java.awt.Insets(2, 8, 2, 8));
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        jLabelMetabolismo.setText("Metabolismo Basal");

        jTextFieldMetBas.setEditable(false);
        jTextFieldMetBas.setBackground(new java.awt.Color(204, 204, 255));

        jLabelkcal.setText("kcal");

        jLabelCalMantPeso.setText("Calorías para mantener peso");

        jTextFieldMantPes.setEditable(false);
        jTextFieldMantPes.setBackground(new java.awt.Color(204, 204, 255));

        jLabelkc.setText("kcal");

        jLabelCC.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelCC.setText("Calculo de calorías");

        jTextAreaErrores.setEditable(false);
        jTextAreaErrores.setBackground(new java.awt.Color(255, 204, 204));
        jTextAreaErrores.setColumns(20);
        jTextAreaErrores.setRows(5);
        jTextAreaErrores.setBorder(javax.swing.BorderFactory.createTitledBorder("Se han encontrado las siguientes errores"));
        jScrollPane1.setViewportView(jTextAreaErrores);
        jTextAreaErrores.getAccessibleContext().setAccessibleName("");
        jTextAreaErrores.getAccessibleContext().setAccessibleDescription("");

        jButtonCerrarErrores.setText("X");
        jButtonCerrarErrores.setToolTipText("Cerrar Errores");
        jButtonCerrarErrores.setMargin(new java.awt.Insets(2, 4, 2, 4));
        jButtonCerrarErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarErroresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelErroresLayout = new javax.swing.GroupLayout(jPanelErrores);
        jPanelErrores.setLayout(jPanelErroresLayout);
        jPanelErroresLayout.setHorizontalGroup(
            jPanelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelErroresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanelErroresLayout.createSequentialGroup()
                        .addGap(0, 457, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarErrores)))
                .addGap(33, 33, 33))
        );
        jPanelErroresLayout.setVerticalGroup(
            jPanelErroresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelErroresLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCerrarErrores))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelPeso)
                                .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelAltura)
                                .addComponent(jLabelEdad)
                                .addComponent(jLabelActividad)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCalMantPeso)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBoxGenero, 0, 116, Short.MAX_VALUE)
                                                .addComponent(jTextFieldPeso)
                                                .addComponent(jTextFieldAltura))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel_kg))
                                        .addComponent(jLabel_cm))
                                    .addComponent(jLabelCC)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelMetabolismo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel_años)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMantPes, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jTextFieldMetBas))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelkcal)
                            .addComponent(jLabelkc))
                        .addGap(32, 32, 32))
                    .addComponent(jPanelErrores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeso)
                    .addComponent(jTextFieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_kg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAltura)
                    .addComponent(jTextFieldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_cm))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEdad)
                    .addComponent(jLabel_años))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelActividad)
                    .addComponent(jComboBoxActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular)
                    .addComponent(jLabelMetabolismo)
                    .addComponent(jTextFieldMetBas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelkcal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCalMantPeso)
                    .addComponent(jTextFieldMantPes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelkc))
                .addGap(39, 39, 39)
                .addComponent(jPanelErrores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed


    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jTextFieldPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed

        double peso;
        int altura;
        int edad;
        double metBasal;
        double calorias;

        StringBuilder sb = new StringBuilder();

        jTextFieldMetBas.setText("");
        jTextFieldMantPes.setText("");
        jTextAreaErrores.setText("");

        if (jTextFieldPeso.getText().isEmpty()) {
            sb.append("  - El peso no puede quedar en blanco\n");
        } else if (!Convert.isValidDouble(jTextFieldPeso.getText())) {
            sb.append("  - El peso tiene que ser formato adecuado\n");
        }

        if (jTextFieldAltura.getText().isEmpty()) {
            sb.append("  - La altura no puede quedar en blanco\n");
        } else if (!Convert.isValidInt(jTextFieldAltura.getText())) {
            sb.append("  - La altura tiene que ser formato adecuado\n");
        }

        if (jTextFieldEdad.getText().isEmpty()) {
            sb.append("  - La edad no puede quedar en blanco\n");
        } else if (!Convert.isValidInt(jTextFieldEdad.getText())) {
            sb.append("  - La edad tiene que ser formato adecuado\n");
        }

        if (sb.length() > 0) {
            jPanelErrores.setVisible(true);
            setSize(550, 600);
            jTextAreaErrores.append(sb.toString());
            jTextAreaErrores.setCaretPosition(0);
            return;
        }

        peso = Convert.parseDouble(jTextFieldPeso.getText());
        altura = Convert.parseInt(jTextFieldAltura.getText());
        edad = Convert.parseInt(jTextFieldEdad.getText());

        metaBasal.setGenero(jComboBoxGenero.getSelectedItem().toString());
        metaBasal.setPeso(peso);
        metaBasal.setAltura(altura);
        metaBasal.setEdad(edad);
        metaBasal.setActividad(jComboBoxActividad.getSelectedItem().toString());

        if (metaBasal.validate() == false) {
            jPanelErrores.setVisible(true);
            setSize(550, 600);
            sb.append(metaBasal.getMensaje());
            jTextAreaErrores.append(sb.toString());
            jTextAreaErrores.setCaretPosition(0);
            return;
        }

        metBasal = metaBasal.getMetabolismoBasal();
        calorias = metaBasal.getCaloriasMantenerPeso();

        jTextFieldMetBas.setText(Convert.format(metBasal, 2));
        jTextFieldMantPes.setText(Convert.format(calorias, 2));

        jPanelErrores.setVisible(false);
        setSize(550, 450);


    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonCerrarErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarErroresActionPerformed
        jPanelErrores.setVisible(false);
        setSize(550, 450);
    }//GEN-LAST:event_jButtonCerrarErroresActionPerformed

    private void jComboBoxActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActividadActionPerformed

    }//GEN-LAST:event_jComboBoxActividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonCerrarErrores;
    private javax.swing.JComboBox<String> jComboBoxActividad;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabelActividad;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelCC;
    private javax.swing.JLabel jLabelCalMantPeso;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelMetabolismo;
    private javax.swing.JLabel jLabelPeso;
    private javax.swing.JLabel jLabel_años;
    private javax.swing.JLabel jLabel_cm;
    private javax.swing.JLabel jLabel_kg;
    private javax.swing.JLabel jLabelkc;
    private javax.swing.JLabel jLabelkcal;
    private javax.swing.JPanel jPanelErrores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaErrores;
    private javax.swing.JTextField jTextFieldAltura;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldMantPes;
    private javax.swing.JTextField jTextFieldMetBas;
    private javax.swing.JTextField jTextFieldPeso;
    // End of variables declaration//GEN-END:variables
}
